name: Code Test and docker devkit-deno image build 

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run:  |
          docker build \
            --build-arg USERNAME=$(whoami) \
            --build-arg USER_UID=$(id -u) \
            --build-arg USER_GID=$(id -g) \
            --target devkit-deno \
            -t deno-container \
            -f .devcontainer/Dockerfile .

      - name: Run tests and generate coverage
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspaces \
            deno-container \
            deno task test

      # - name: Generate documentation
      #   run: |
      #     docker run --rm \
      #       -v ${{ github.workspace }}:/workspaces \
      #       deno-container \
      #       deno task doc

      # - name: Setup Pages
      #   uses: actions/configure-pages@v4

      # - name: Prepare artifacts for upload
      #   run: |
      #     mkdir -p ./doc/coverage
      #     mkdir -p ./doc/documentation
      #     cp -r ./coverage/html/* ./doc/coverage/
      #     cp -r ./documentation/* ./doc/documentation/

      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: './doc'

      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: .devcontainer/Dockerfile
          context: .
          target: cfx-deno-cli
          push: true
          tags: cfxdevkit/cfx-deno-cli-ci

      - name: Log out from Docker Hub
        run: docker logout