name: Release on tag 

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run:  |
          docker build \
            --build-arg USERNAME=$(whoami) \
            --build-arg USER_UID=$(id -u) \
            --build-arg USER_GID=$(id -g) \
            --target devkit-deno \
            -t deno-container \
            -f .devcontainer/Dockerfile .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: devkit-${{  github.ref_name }}.tar.gz

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push cfx-deno-cli Docker image
        uses: docker/build-push-action@v6
        with:
          file: .devcontainer/Dockerfile
          context: .
          target: cfx-deno-cli
          push: true
          tags: |
            cfxdevkit/devkit-cli:${{ github.ref_name }}
            cfxdevkit/devkit-cli:latest

      - name: Build and push devkit-nvm Docker image
        uses: docker/build-push-action@v6
        with:
          file: .devcontainer/Dockerfile
          context: .
          target: devkit-nvm
          push: true
          tags: |
            cfxdevkit/devkit-nvm:${{ github.ref_name }}
            cfxdevkit/devkit-nvm:latest

      - name: Build and push devkit-hardhat Docker image
        uses: docker/build-push-action@v6
        with:
          file: .devcontainer/Dockerfile
          context: .
          target: devkit-hardhat
          push: true
          tags: |
            cfxdevkit/devkit-hardhat:${{ github.ref_name }}
            cfxdevkit/devkit-hardhat:latest

      # - name: Build and push devkit-hardhat-core Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     file: .devcontainer/Dockerfile
      #     context: .
      #     target: devkit-hardhat-core
      #     push: true
      #     tags: |
      #       cfxdevkit/devkit-hardhat-core:${{ github.ref_name }}
      #       cfxdevkit/devkit-hardhat-core:latest

      # - name: Build and push devkit-hardhat Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     file: .devcontainer/Dockerfile
      #     context: .
      #     target: devkit-hardhat-espace
      #     push: true
      #     tags: |
      #       cfxdevkit/devkit-hardhat-espace:${{ github.ref_name }}
      #       cfxdevkit/devkit-hardhat-espace:latest

      - name: Log out from Docker Hub
        run: docker logout